### ISSUE TITLE
The path "domain-functions" is imported in "..." but "domain-functions" was not found in your node_modules. Did you forget to install it?

### ISSUE THREAD

**Issue by alexbu92** [seasonedcc/composable-functions#40] opened 2022-09-21 15:57 UTC
Getting this error in Remix project, when building, when starting it gives this:
`Error: No "exports" main defined in .../node_modules/domain-functions/package.json`

**Comment by Jose4gg** [comment] 2022-09-21 16:21
@gustavoguichard this is happening only on `1.0.1` I went back to `1.0.1` and the error is gone.

**Comment by gustavoguichard** [comment] 2022-09-21 16:23
@Jose4gg Ok, I'll investigate further. We are making some changes so the package can be used on DenoJS from 1.0.1.
No other changes, so keep at the 1.0.0 version until I close this issue ;D

**Comment by gustavoguichard** [comment] 2022-09-21 17:07
@Jose4gg and @alexbu92 I couldn't replicate the issue. 
Are you guys using CommonJS imports?

If not, could you try running:
```shell 
npm update
npm audit fix --force
```

And LMK if it works for you?

**Comment by diogob** [comment] 2022-09-21 17:10
also @Jose4gg what is your Node.JS version?

**Closed as completed** 2022-09-21 18:42 UTC

**Comment by gustavoguichard** [comment] 2022-09-21 18:52
@Jose4gg and @alexbu92 could you guys try to use the `domain-functions@1.0.2` and let us know if the issue is fixed?
