### ISSUE TITLE
[Bug]: failed parse FormData with Cloudflare

### ISSUE THREAD

**Issue by ergofriend** [seasonedcc/composable-functions#18] opened 2022-04-21 15:35 UTC
## What version
0.0.2

## What happend
[input-resolvers.ts#L6-L7](https://github.com/SeasonedSoftware/remix-domains/blob/main/src/input-resolvers.ts#L6-L7) failed parse FormData with Cloudflare Pages functions.

## Steps to Reproduce

I found that `new URLSearchParams().toString()` return `""` with Cloudflare Pages functions  at [ergofriend/remix-cloudflare-pages](https://github.com/ergofriend/remix-cloudflare-pages/blob/c665cc7d1ca140cf03adacde753a68871621dd8e/app/service/vote.ts#L53-L56)

### debug code
```ts
const formData = await request.clone().formData()
const data = new URLSearchParams(formData as URLSearchParams).toString()
const json = JSON.stringify(Object.fromEntries(formData.entries()))
sentry.captureMessage(`action URLSearchParams: ${JSON.stringify(data)} json: ${json}`)
```

### sentry.io console
```
// local (wrangler2)
action URLSearchParams: "like=takenoko" json: {"like":"takenoko"}

// cloudflare pages functions
action URLSearchParams: "" json: {"like":"takenoko"}
```

**Comment by diogob** [comment] 2022-04-21 20:58
@ergofriend it seems to be an issue with the remix cloudflare adapter. I'll investigate the issue further, and perhaps there is an elegant work-around on our end.

**Comment by diogob** [comment] 2022-04-21 21:02
In the meantime you can just pass `Object.fromEntries(formData.entries())` to your domain function if you don't need fancy structured data provided by `qs`. Or `qs(await request.clone().text())` in case you need the fancy structured and the form is not a multipart encoded.

**Comment by diogob** [comment] 2022-04-22 14:24
@ergofriend could you try reproducing the issue using the package from the branch `cloudflare-adapter-workaround` ?
You can install locally by using the following entry in your `package.json`: 
```
    "remix-domains": "github:SeasonedSoftware/remix-domains#cloudflare-adapter-workaround",
```

If the error persists you should report the issue in the [remix repo](https://github.com/remix-run/remix) since the cloudflare adapter would have to be fixed.

**Comment by ergofriend** [comment] 2022-04-22 16:39
thx, but I got same error `Invalid enum value. Expected 'takenoko' | 'kinoko'`.
And console debug said same result as below.
```
// local
action data: like=takenoko newData: like=takenoko json: {"like":"takenoko"}
// cloudflare
action data:  newData:  json: {"like":"takenoko"}
```

Exactly, I will report to remix, thank you for your cooperation.

**Comment by gustavoguichard** [comment] 2022-05-08 02:24
I'm closing this issue as it seems to be a problem with Cloudflare's adapter. Feel free to file another issue if you think the problem is in this repo ;)

**Closed as completed by gustavoguichard** 2022-05-08 02:24 UTC
